//OPENING instructions
var openInst = "Welcome to the Dot Motion and Confidence study.\
Before we start we need to configure the experimental setup.\
"

//practice block instructions
var pInst = "This is a prctice block. <br>In a trial you will be seeing rondom dots moving around in the center of screen in a circular aperture. Your task is to determine the DOMINANT direvtion of motion with a level of confidence which you will report by pressing a key within 1 seconds. <br>If you have wish to report with: <br>&emsp;1.a) High confidence in Left direction use D key, <br>&emsp;1.b) Low confidence in Left direction use S key, <br>&emsp;2.a) High confidence in Right direction use K key, <br>&emsp;2.b) Low confidence in Right direction use L key<br>After you have given the response a feedback will be presented informing you whether you reported the correct direction or not.<br>You have to respond within 3 seconds starting from the display of dots. Dots will stop being in motion after some milliseconds. If you fail to respond, the feedback message: 'failed to respond' will be displayed.<br>To start a new trial press either C or M key<br>To qualify for main experimental blocks you have to have respond accuartely and as fast as possible. <br>Practice Block continue unless you achieve a threshold accuracy. <br>Fixating on the cross at the center of the screen will be helpful in performing the task."
//experiment block 1 instructions
var e1Inst = "This is a Experiment part 1. <br>You have to do respond in the same way as in the Practice block. The response time is same as that before, that is, you have to respond within 3 seconds of the display of the dots.<br>You will be given no feedback on the correctness of the response and the failure to report.<br>The other difference here is that dots can appear in either blue or yellow color. Although the color keeps on changing from one trial to another, you have to respond on the direction of DOMINANT motion of the dots in that trial with a certain degree of confidence by pressing a key, the same way you did in the practice block.<br>To start a new trial press either C key or M key.<br>Try to respond accuartely and as fast as possible."

//experiment block 2 instructions
var e2Inst = "This is a Experiment part 2. It is in two blocks.<br>Begining of each trial you have to CHOOSE the COLOR of DOTS. To Choose Yellow press C and to Choose Blue Press M.<br>You have to do respond in the same way as in the Practice block. The response time is same as that before, that is, you have to respond within 3 seconds of the display of the dots.<br>You will be given no feedback on the correctness of the response and the failure to report.<br>The other difference here is that dots can appear in either blue or yellow color. Although the color keeps on changing from one trial to another, you have to respond on the direction of DOMINANT motion of the dots in that trial with a certain degree of confidence by pressing a key, the same way you did in the practice block.<br>To start a new trial press either C key or M key.<br>Try to respond accuartely and as fast as possible."